# Script to add transport reactions to models generated by gapseq.
# Usage:
# Rscript edit_metabat1.59_model.R input_model output_model
# input_model --> Full path to original RDS draft model
# output_model --> Full path where the modified RDS model is going to be stored

library("sybil")

input_model <- args[1] # path to draft model
model <- readRDS(input_model)

# Add missing transport reactions
# asparagine
model <- addReact(model, id = "rxn08160_c0",
    met = c("cpd00001[c0]", "cpd00002[c0]", "cpd00132[e0]",
    "cpd00009[c0]", "cpd00067[c0]", "cpd00008[c0]", "cpd00132[c0]"),
    Scoef = c(-1, -1, -1, 1, 1, 1, 1),
    metComp = c("c0", "c0", "e0", "c0", "c0", "c0", "c0"),
    gprAssoc = paste0("metabat1.59__contig889_1685 ",
    "or metabat1.59__contig889_157"),
    reversible = FALSE, lb = 0, ub = 1000, obj = 0)
# serine
model <- addReact(model, id = "rxn10883_c0",
    met = c("cpd00001[c0]", "cpd00002[c0]", "cpd00054[e0]",
    "cpd00009[c0]", "cpd00067[c0]", "cpd00008[c0]", "cpd00054[c0]"),
    Scoef = c(-1, -1, -1, 1, 1, 1, 1),
    metComp = c("c0", "c0", "e0", "c0", "c0", "c0", "c0"),
    gprAssoc = "metabat1.59__contig889_157",
    reversible = FALSE, lb = 0, ub = 1000, obj = 0)
# arginine
model <- addReact(model, id = "rxn05154_c0",
    met = c("cpd00001[c0]", "cpd00002[c0]", "cpd00051[e0]",
    "cpd00009[c0]", "cpd00067[c0]", "cpd00008[c0]", "cpd00051[c0]"),
    Scoef = c(-1, -1, -1, 1, 1, 1, 1),
    metComp = c("c0", "c0", "e0", "c0", "c0", "c0", "c0"),
    gprAssoc = paste0("metabat1.59__contig889_1685 ",
    "or metabat1.59__contig889_157"),
    reversible = FALSE, lb = 0, ub = 1000, obj = 0)
# glycine
model <- addReact(model, id = "rxn10862_c0",
    met = c("cpd00001[c0]", "cpd00002[c0]", "cpd00033[e0]",
    "cpd00009[c0]", "cpd00067[c0]", "cpd00008[c0]", "cpd00033[c0]"),
    Scoef = c(-1, -1, -1, 1, 1, 1, 1),
    metComp = c("c0", "c0", "e0", "c0", "c0", "c0", "c0"),
    gprAssoc = "metabat1.59__contig889_1238",
    reversible = FALSE, lb = 0, ub = 1000, obj = 0)
# aspartate
model <- addReact(model, id = "rxn05152_c0",
    met = c("cpd00001[c0]", "cpd00002[c0]", "cpd00041[e0]",
    "cpd00009[c0]", "cpd00067[c0]", "cpd00008[c0]", "cpd00041[c0]"),
    Scoef = c(-1, -1, -1, 1, 1, 1, 1),
    metComp = c("c0", "c0", "e0", "c0", "c0", "c0", "c0"),
    gprAssoc = "metabat1.59__contig889_1685",
    reversible = FALSE, lb = 0, ub = 1000, obj = 0)
# glutamate
model <- addReact(model, id = "rxn05297_c0",
    met = c("cpd00023[e0]", "cpd00067[e0]",
    "cpd00023[c0]", "cpd00067[c0]"),
    Scoef = c(-1, -1, 1, 1),
    metComp = c("e0", "e0", "c0", "c0"),
    gprAssoc = "metabat1.59__contig889_1363",
    reversible = TRUE, lb = -1000, ub = 1000, obj = 0)
model <- addReact(model, id = "rxn05146_c0",
    met = c("cpd00001[c0]", "cpd00002[c0]", "cpd00023[e0]",
    "cpd00009[c0]", "cpd00067[c0]", "cpd00008[c0]", "cpd00023[c0]"),
    Scoef = c(-1, -1, -1, 1, 1, 1, 1),
    metComp = c("c0", "c0", "e0", "c0", "c0", "c0", "c0"),
    gprAssoc = paste0("metabat1.59__contig889_1685 ",
    "or metabat1.59__contig889_157"),
    reversible = FALSE, lb = 0, ub = 1000, obj = 0)
# threonine
model <- addReact(model, id = "rxn05169_c0",
    met = c("cpd00001[c0]", "cpd00002[c0]", "cpd00161[e0]",
    "cpd00009[c0]", "cpd00067[c0]", "cpd00008[c0]", "cpd00161[c0]"),
    Scoef = c(-1, -1, -1, 1, 1, 1, 1),
    metComp = c("c0", "c0", "e0", "c0", "c0", "c0", "c0"),
    gprAssoc = "metabat1.59__contig889_157",
    reversible = FALSE, lb = 0, ub = 1000, obj = 0)
# alanine
model <- addReact(model, id = "rxn08097_c0",
    met = c("cpd00001[c0]", "cpd00002[c0]", "cpd00035[e0]",
    "cpd00009[c0]", "cpd00067[c0]", "cpd00008[c0]", "cpd00035[c0]"),
    Scoef = c(-1, -1, -1, 1, 1, 1, 1),
    metComp = c("c0", "c0", "e0", "c0", "c0", "c0", "c0"),
    gprAssoc = "metabat1.59__contig889_157",
    reversible = FALSE, lb = 0, ub = 1000, obj = 0)
# proline
model <- addReact(model, id = "rxn05165_c0",
    met = c("cpd00001[c0]", "cpd00002[c0]", "cpd00129[e0]",
    "cpd00009[c0]", "cpd00067[c0]", "cpd00008[c0]", "cpd00129[c0]"),
    Scoef = c(-1, -1, -1, 1, 1, 1, 1),
    metComp = c("c0", "c0", "e0", "c0", "c0", "c0", "c0"),
    gprAssoc = "metabat1.59__contig889_157",
    reversible = FALSE, lb = 0, ub = 1000, obj = 0)
# lysine
model <- addReact(model, id = "rxn05151_c0",
    met = c("cpd00001[c0]", "cpd00002[c0]", "cpd00039[e0]",
    "cpd00009[c0]", "cpd00067[c0]", "cpd00008[c0]", "cpd00039[c0]"),
    Scoef = c(-1, -1, -1, 1, 1, 1, 1),
    metComp = c("c0", "c0", "e0", "c0", "c0", "c0", "c0"),
    gprAssoc = paste0("metabat1.59__contig889_1685 ",
    "or metabat1.59__contig889_157"),
    reversible = FALSE, lb = 0, ub = 1000, obj = 0)
# valine
model <- addReact(model, id = "rxn05168_c0",
    met = c("cpd00001[c0]", "cpd00002[c0]", "cpd00156[e0]",
    "cpd00009[c0]", "cpd00067[c0]", "cpd00008[c0]", "cpd00156[c0]"),
    Scoef = c(-1, -1, -1, 1, 1, 1, 1),
    metComp = c("c0", "c0", "e0", "c0", "c0", "c0", "c0"),
    gprAssoc = "metabat1.59__contig889_157",
    reversible = FALSE, lb = 0, ub = 1000, obj = 0)
# isoleucine
model <- addReact(model, id = "rxn05179_c0",
    met = c("cpd00001[c0]", "cpd00002[c0]", "cpd00322[e0]",
    "cpd00009[c0]", "cpd00067[c0]", "cpd00008[c0]", "cpd00322[c0]"),
    Scoef = c(-1, -1, -1, 1, 1, 1, 1),
    metComp = c("c0", "c0", "e0", "c0", "c0", "c0", "c0"),
    gprAssoc = "metabat1.59__contig889_1068",
    reversible = FALSE, lb = 0, ub = 1000, obj = 0)
# leucine
model <- addReact(model, id = "rxn05161_c0",
    met = c("cpd00001[c0]", "cpd00002[c0]", "cpd00107[e0]",
    "cpd00009[c0]", "cpd00067[c0]", "cpd00008[c0]", "cpd00107[c0]"),
    Scoef = c(-1, -1, -1, 1, 1, 1, 1),
    metComp = c("c0", "c0", "e0", "c0", "c0", "c0", "c0"),
    gprAssoc = "metabat1.59__contig889_1068",
    reversible = FALSE, lb = 0, ub = 1000, obj = 0)
# phenylalanine
model <- addReact(model, id = "rxn18584_c0",
    met = c("cpd00001[c0]", "cpd00002[c0]", "cpd00066[e0]",
    "cpd00009[c0]", "cpd00067[c0]", "cpd00008[c0]", "cpd00066[c0]"),
    Scoef = c(-1, -1, -1, 1, 1, 1, 1),
    metComp = c("c0", "c0", "e0", "c0", "c0", "c0", "c0"),
    gprAssoc = "metabat1.59__contig889_1068",
    reversible = FALSE, lb = 0, ub = 1000, obj = 0)

# Add missing exchange reactions
mets <- c("cpd00132", "cpd00054", "cpd00051", "cpd00033",
    "cpd00041", "cpd00023", "cpd00161", "cpd00035",
    "cpd00129", "cpd00039", "cpd00156", "cpd00322",
    "cpd00107", "cpd00066")
for (met in mets) {
    model <- addReact(model, id = paste0("EX_", met, "_e0"),
        reactName = paste0(met, "[e0] Exchange"),
        met = paste0(met, "[e0]"),
        Scoef = -1,
        metComp = "e0",
        reversible = TRUE, lb = -1000, ub = 1000, obj = 0)
}

output_model <- args[2] # path to curated draft model
saveRDS(model, output_model)
